//! i3-native keybinding export.
//!
//! This backend makes DeskHalloumi the declarative source of truth while i3 keeps
//! ownership of X11 passive grabs. It is the safe migration path for ordinary
//! sxhkd press/release bindings: matching keys are consumed by i3 and do not
//! leak into the focused client, unlike an observing evdev listener.

use crate::key_engine::KeyTrigger;
use crate::keys::{CommandType, KeyBinding};
use std::collections::HashMap;

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct I3ExportOptions {
    /// Executable used for managed menu actions.
    pub hotkey_client: String,
}

impl Default for I3ExportOptions {
    fn default() -> Self {
        Self {
            hotkey_client: "deskhalloumi-hotkeyd".to_string(),
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct I3ExportResult {
    pub config: String,
    pub warnings: Vec<String>,
    pub exported_count: usize,
    pub skipped_count: usize,
}

/// Render bindings as an i3 include file.
///
/// Press and release bindings are exact for the supported key grammar. Hold,
/// modifier-release and repeat bindings are skipped because i3 cannot express
/// those semantics faithfully. Unsupported action types are also skipped
/// rather than silently changing behavior.
pub fn render_i3_bindings(bindings: &[KeyBinding], options: &I3ExportOptions) -> I3ExportResult {
    let mut result = I3ExportResult::default();
    let mut lines = vec![
        "# Generated by deskhalloumi-hotkeyd. Do not edit this file directly.".to_string(),
        "# Add: include ~/.config/deskhalloumi/i3-bindings.conf".to_string(),
        "# Regenerate from the canonical DeskHalloumi TOML or sxhkd source.".to_string(),
        String::new(),
    ];
    let mut emitted = HashMap::<String, String>::new();

    for binding in bindings {
        let trigger = effective_trigger(binding);
        let release_flag = match trigger {
            KeyTrigger::Press => "",
            KeyTrigger::Release => " --release",
            KeyTrigger::Modrelease => {
                result.warnings.push(format!(
                    "{}: skipped trigger=modrelease; i3 has no hold/modifier-release equivalent",
                    binding.name
                ));
                result.skipped_count += 1;
                continue;
            }
            KeyTrigger::Repeat => {
                result.warnings.push(format!(
                    "{}: skipped trigger=repeat; i3 repeat behavior is not equivalent",
                    binding.name
                ));
                result.skipped_count += 1;
                continue;
            }
        };

        let chord = match canonical_i3_chord(&binding.keysym) {
            Ok(chord) => chord,
            Err(error) => {
                result
                    .warnings
                    .push(format!("{}: skipped: {error}", binding.name));
                result.skipped_count += 1;
                continue;
            }
        };

        let command = match i3_command(binding, options) {
            Ok(command) => command,
            Err(error) => {
                result
                    .warnings
                    .push(format!("{}: skipped: {error}", binding.name));
                result.skipped_count += 1;
                continue;
            }
        };

        if binding.hold_ms.unwrap_or(0) > 0 {
            result.warnings.push(format!(
                "{}: hold_ms is ignored by the i3 backend",
                binding.name
            ));
        }
        if binding.cooldown_ms.is_some() {
            result.warnings.push(format!(
                "{}: cooldown_ms is ignored by the i3 backend",
                binding.name
            ));
        }
        if binding.priority != 0 || binding.consume {
            result.warnings.push(format!(
                "{}: priority/consume conflict policy is not available in i3; duplicate chords must be resolved before export",
                binding.name
            ));
        }

        let identity = format!("{chord}:{release_flag}");
        if let Some(previous) = emitted.insert(identity, binding.name.clone()) {
            result.warnings.push(format!(
                "{}: duplicate i3 chord also emitted by {}; i3 ownership would be ambiguous",
                binding.name, previous
            ));
        }

        lines.push(format!("# {}", binding.name));
        lines.push(format!(
            "bindsym{release_flag} {chord} exec --no-startup-id {}",
            i3_quote(&command)
        ));
        result.exported_count += 1;
    }

    if result.exported_count == 0 {
        lines.push("# No bindings were exportable.".to_string());
    }
    lines.push(String::new());
    result.config = lines.join("\n");
    result
}

fn effective_trigger(binding: &KeyBinding) -> KeyTrigger {
    if binding.release && matches!(binding.trigger, KeyTrigger::Press) {
        KeyTrigger::Release
    } else {
        binding.trigger.clone()
    }
}

fn i3_command(binding: &KeyBinding, options: &I3ExportOptions) -> Result<String, String> {
    if binding.command.contains(['\n', '\r']) {
        return Err("multiline commands cannot be emitted into an i3 include".to_string());
    }
    match binding.command_type {
        CommandType::Shell => Ok(binding.command.clone()),
        CommandType::Menu => Ok(format!(
            "{} --menu-action {}",
            shell_word(&options.hotkey_client),
            shell_word(&binding.command)
        )),
        CommandType::Bar | CommandType::Tray | CommandType::Widget => Err(format!(
            "type={:?} requires an embedded action receiver and cannot be exported safely",
            binding.command_type
        )),
    }
}

pub fn canonical_i3_chord(keysym: &str) -> Result<String, String> {
    let tokens = keysym
        .split('+')
        .map(str::trim)
        .filter(|token| !token.is_empty())
        .map(i3_token)
        .collect::<Result<Vec<_>, _>>()?;
    if tokens.len() < 2 {
        return Err(format!(
            "keysym '{keysym}' must contain a modifier and a trigger key for safe global export"
        ));
    }
    Ok(tokens.join("+"))
}

fn i3_token(token: &str) -> Result<String, String> {
    let normalized = token.trim().to_ascii_uppercase().replace(['-', ' '], "_");
    let bare = normalized.strip_prefix("KEY_").unwrap_or(&normalized);
    let mapped = match bare {
        "SUPER" | "META" | "WIN" | "WINDOWS" | "LEFTMETA" | "RIGHTMETA" => "Mod4",
        "ALT" | "LEFTALT" | "RIGHTALT" => "Mod1",
        "CTRL" | "CONTROL" | "LEFTCTRL" | "RIGHTCTRL" => "Control",
        "SHIFT" | "LEFTSHIFT" | "RIGHTSHIFT" => "Shift",
        "RETURN" | "ENTER" => "Return",
        "ESC" | "ESCAPE" => "Escape",
        "SPACE" => "space",
        "TAB" => "Tab",
        "BACKSPACE" => "BackSpace",
        "DELETE" | "DEL" => "Delete",
        "PAGEUP" | "PAGE_UP" => "Prior",
        "PAGEDOWN" | "PAGE_DOWN" => "Next",
        "HOME" => "Home",
        "END" => "End",
        "UP" => "Up",
        "DOWN" => "Down",
        "LEFT" => "Left",
        "RIGHT" => "Right",
        "MINUS" => "minus",
        "EQUAL" => "equal",
        "COMMA" => "comma",
        "DOT" | "PERIOD" => "period",
        "SLASH" => "slash",
        "SEMICOLON" => "semicolon",
        "APOSTROPHE" => "apostrophe",
        "LEFTBRACE" | "BRACKETLEFT" => "bracketleft",
        "RIGHTBRACE" | "BRACKETRIGHT" => "bracketright",
        "BACKSLASH" => "backslash",
        "GRAVE" => "grave",
        value if value.len() == 1 && value.chars().all(|c| c.is_ascii_alphabetic()) => {
            return Ok(value.to_ascii_lowercase());
        }
        value if value.len() == 1 && value.chars().all(|c| c.is_ascii_digit()) => value,
        value
            if value.starts_with('F')
                && value.len() <= 3
                && value[1..].chars().all(|c| c.is_ascii_digit()) =>
        {
            value
        }
        _ => return Err(format!("unsupported i3 key token '{token}'")),
    };
    Ok(mapped.to_string())
}

fn i3_quote(value: &str) -> String {
    format!("\"{}\"", value.replace('\\', "\\\\").replace('"', "\\\""))
}

fn shell_word(value: &str) -> String {
    if value
        .chars()
        .all(|character| character.is_ascii_alphanumeric() || "_./:-".contains(character))
    {
        return value.to_string();
    }
    format!("'{}'", value.replace('\'', "'\\''"))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn binding(name: &str, keysym: &str, command: &str) -> KeyBinding {
        KeyBinding {
            name: name.to_string(),
            keysym: keysym.to_string(),
            command: command.to_string(),
            command_type: CommandType::Shell,
            release: false,
            trigger: KeyTrigger::Press,
            hold_ms: None,
            cooldown_ms: None,
            priority: 0,
            consume: false,
        }
    }

    #[test]
    fn exports_press_and_release_bindings_with_i3_keysyms() {
        let press = binding("terminal", "Super+Return", "alacritty");
        let mut release = binding("launcher", "Ctrl+Alt+space", "rofi -show drun");
        release.trigger = KeyTrigger::Release;
        let result = render_i3_bindings(&[press, release], &I3ExportOptions::default());
        assert_eq!(result.exported_count, 2);
        assert_eq!(result.skipped_count, 0);
        assert!(result.config.contains("bindsym Mod4+Return"));
        assert!(
            result
                .config
                .contains("bindsym --release Control+Mod1+space")
        );
    }

    #[test]
    fn menu_binding_calls_hotkey_client() {
        let mut menu = binding("menu", "Super+i", "toggle:i3-vis");
        menu.command_type = CommandType::Menu;
        let result = render_i3_bindings(&[menu], &I3ExportOptions::default());
        assert!(
            result
                .config
                .contains("deskhalloumi-hotkeyd --menu-action toggle:i3-vis")
        );
    }

    #[test]
    fn skips_semantics_i3_cannot_represent() {
        let mut binding = binding("hold", "Super+space", "echo hold");
        binding.trigger = KeyTrigger::Modrelease;
        let result = render_i3_bindings(&[binding], &I3ExportOptions::default());
        assert_eq!(result.exported_count, 0);
        assert_eq!(result.skipped_count, 1);
        assert!(result.warnings[0].contains("modrelease"));
    }

    #[test]
    fn warns_for_duplicate_chords() {
        let first = binding("first", "Super+x", "one");
        let second = binding("second", "Meta+x", "two");
        let result = render_i3_bindings(&[first, second], &I3ExportOptions::default());
        assert!(
            result
                .warnings
                .iter()
                .any(|line| line.contains("duplicate"))
        );
    }
}
